### ISSUE TITLE
Add way to paste in HTML in the email

### ISSUE THREAD

**Issue by CarlJKashnier** [freeCodeCamp/mail-for-good#100]

**Comment by AndrewGHC** [comment]
I've done a fair bit of reading on this and the conclusion is that there are no open source email template editors. There are plain/rich text editors that use html, but they lack the power of a fully fledged template editor.

My suggestion is that we could create our own email template editor that could be abstracted to a powerful HTML editor as a separate project (would take too long to do this for the MVP, and would need to be a separate project). If we did so, it would be the first truly open source & free variant of its kind.

**Comment by CarlJKashnier** [comment]
Have you checked out tinyMCE? It is used all over the place for HTML
editing plus you can dump html straight into it. It supports tables and a
bunch of other stuff.

It is licensed under the lesser public gnu license so it would seem we can
use it.

It is used by quite a few companies including wordpress, microsoft, ibm.
About 100M wevsite use it.

**Comment by AndrewGHC** [comment]
Sorry for the delay in getting back to you on this Carl.

TinyMCE is a great editor and it's one we checked out. Only problem is that it's just a rich text editor, it's not designed to handle complex html email templates.

From my research, there's only one open source editor for this purpose that we could use - https://mosaico.io/. The problem is that its license is restrictive and it would take a while to integrate it.

My suggestion is that we exclude complex email templates from the MVP as there's no simple way around this at this stage. It's likely that we'd have to write our own email template editor, which would be the first open source free variant of its kind.

**Comment by karuppiah7890** [comment]
@AndrewGHC I have actually tried out Mosaico and it's pretty neat! We can take inspiration from it if we write our own, and it uses tinyMCE only I think

**Comment by kleebaker** [comment]
Is this also related to #114 and #115?
