### ISSUE TITLE
As a user, I should be able to delete an unsent campaign to prevent myself from later accidentally sending it

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/mail-for-good#111]
I couldn't figure out a way to delete an unsent campaign. I am worried I might unthinkingly send out an old campaign to 700k people, so it would be best if there was a mechanism for deleting it completely to eliminate that possibility.

**Comment by karuppiah7890** [comment]
@QuincyLarson In the current version, I think the application disables the send buttons on completed campaigns. I also tried to enable the button on client side and send, to test how it is handled on server side. But I couldn't really send the mail even after enabling the button

**Comment by karuppiah7890** [comment]
Oops. I just understood what you meant. I missed the word "unsent". Actually, I just thought about this use case.

So, when a user creates a campaign and it's ready and then when he plans to send it, he might notice a mistake in the email. And he might want to delete it. So, I think it's better to provide a delete campaign feature if it's an unsent campaign and also, the delete should be confirmed instead of a single click delete to prevent accidental deletes. 

cc @AndrewGHC

**Comment by AndrewGHC** [comment]
Cheers guys - this is done
