### ISSUE TITLE
Feature to choose SMTP SERVER instead of AWS

### ISSUE THREAD

**Issue by AlienFX** [freeCodeCamp/mail-for-good#161]
Hey there,
Your work looks pretty awesome but why is it required to use it only with AWS ?!
Is it possible for you to add a setting to use with another smtp server ?
Thank you so much in advance :)

**Comment by karuppiah7890** [comment]
I think this might be considered. But for now, the whole tool is modeled around AWS services like SNS, SQS, and SES.

If you ask why ? It's all because SES is dirt cheap. Like, 10,000 mails for $1 is quite cheap. That's why it's all modeled around SES

**Comment by AlienFX** [comment]
Yes you right it's cheap but the rules of AWS are really stricts with high volumes.
That's why it's good to manage his own smtp server. 

Thank you for your answer, hope it's possible in the futur to have this possibility because the client looks very good :)

**Comment by karuppiah7890** [comment]
@AlienFX Yes, I have seen some people trying to use it for high volumes. But AWS is only strict about spams and stuff. You can always justify your reason and ask for a limit increase (emails/day) and send rate (emails/second) increase if all your mails are sent to people who are wanting to receive mails - that is subscribed users or known customers in case of transactional mails or something. In any other case, you cannot use AWS SES, like, especially in Email Marketing - it's quite tough and it's basically a spammer's game, because most people hate getting Ads and marketing mails and they report it as spam and the email clients like Gmail mark those emails as spam and in large scale, it will also black list the mail server. That's why AWS restricts spam because in any other case their server will get blacklisted

**Comment by AlienFX** [comment]
I totally agree with you, but sadly people who registered to your list/service are the same who are reporting you at spam too (ofc not all of them but on high volume it's mean a lot). That's why it's most easier to manage his own smtp server and IPs. Thanks for your time

**Comment by karuppiah7890** [comment]
Mail for Good provides a feature to put an Unsubscribe link in the mails so that users can unsubscribe with just a click

**Comment by AlienFX** [comment]
Yes but people are lazy and sometime prefer to click on the spam button of their client instead of the unsubscribe link... It's a real issue. 
I already saw the README and looks so impressive. I really want to use it :))

**Comment by karuppiah7890** [comment]
Okay..
And oh, nice. Actually, you can test it using SES with AWS Free Tier

**Comment by AlienFX** [comment]
@karuppiah7890 I sent you an email :)

**Comment by karuppiah7890** [comment]
Yes, I just read it

**Comment by AndrewGHC** [comment]
Hi @AlienFX,

It would be fully possible to use other SMTP services, but each addition would require a hefty amount of client and server side code to accommodate them. A modular SMTP lib could be used, with the configuration of each SMTP relay plugged in prior to a campaign send.

We're using AWS' API as HTTP is quite a bit faster that SMTP. An SMTP approach would therefore first need to be configured for this use case.

Other elements of the app are dependant on AWS services however, and these would need to be decoupled. The complexity of integrating multiple relays becomes apparent when trying to keep your own application's state (in terms of bounce rate etc) in sync with data from the relay.

It's not an impossibility though.

**Comment by manjeshpv** [comment]
open source email server compatible with Amazon SES APIs https://github.com/manjeshpv/emailq works with SMTP
