### ISSUE TITLE
Free hosting/deployment

### ISSUE THREAD

**Issue by hsribei** [freeCodeCamp/mail-for-good#181]
Does anybody know of a hosting option where MfG would qualify for a (non time-limited) free tier? Not only the app server, but all dependencies like Redis and Postgres. Thanks!

**Comment by karuppiah7890** [comment]
It's not that easy to get hosting for free. Only some of them provide free hosting for the backend stuff and only some out of them support Docker. In short, they are Zeit Now and Heroku. A long answer is below. 
 
1. Zeit Now. I know you already checked that they don't support docker compose but you could may be find a work around and run three separate containers, but you need to provide strong passwords for your databases since they will be available publicly in this case. You will have to give the hosts for Redis and Postgres, and also the credentials, to the MfG app
2. Heroku. I recently saw they support hosting of Dockerized apps. But I am not sure about composing. Or like I said in the previous one, you have to host it all separately.

**Comment by AndrewGHC** [comment]
@karuppiah7890 Wrapped this up very well. Zeit only offers a way to deploy applications to remote servers in a simple manner, but it doesn't provide hosting. Heroku is a potential option however, the question is one of complexity in terms of setup & the reliability and computational power they can offer.

**Comment by styfle** [comment]
@AndrewGHC Which provider did you pick?

**Comment by AndrewGHC** [comment]
@styfle We're using EC2 instances on the free tier.
