### ISSUE TITLE
Comparison with similar open source tools

### ISSUE THREAD

**Issue by hsribei** [freeCodeCamp/mail-for-good#183]
I'm sure questions of the type "Why not X?" are bound to come up when people are researching Mail for Good and alternatives, so let me begin. 

Are there any alternatives that freeCodeCamp considered or tested before settling on building its own solution? 

One tool I'm not familiar with but that seems to overlap with MfG is [Mautic](https://www.mautic.org), which is also open source. Was there a reason why it was not picked? Thanks!

**Comment by karuppiah7890** [comment]
@hsribei I have actually heard about Mautic. It's more like a solution for automated marketing, which has Email marketing as one of it's features. I also saw that we can use any Email service (including SES) for the [Email Campaign in Mautic](https://mautic.org/docs/en/emails/index.html#email-delivery). 

I think Mail for Good is just a Email Campaign management tool, which uses SES alone for now. And yes, looks like Mautic is a alternative. But I haven't tried it out, so, can't talk about Mautic's performance on Email delivery and stuff. Also, I don't know the hardware requirements (RAM) for running the application. But MfG is quite light weight, and can run on a $10/mo Digital Ocean server. 

Also, as far as I know, Mail for Good was created for users who want to send weekly or monthly newsletters to their subscribers. And that's not the same as Email Marketing. From what I know, Email marketing cannot be done easily with MfG, as Email marketing is mostly about marketing / advertising by sending mails to some new people, whose mails have been obtained by somehow scraping the web. And since MfG uses SES, which strictly prohibits spam and send mails to people who aren't expecting them, who might mark them as spam, it's really tough to use MfG for Email marketing. 

Also, Mautic provides the feature to integrate with any SMTP server or email services. So, that's a good choice over MfG, if marketing (the kind I just explained) is the aim. In case of sending Newsletters to known users, MfG is pretty much a very good choice
