### ISSUE TITLE
Remove port 8080 in URLs in Google API config guide and add missing project creation step

### ISSUE THREAD

**Issue by karuppiah7890** [freeCodeCamp/mail-for-good#203]
https://github.com/freeCodeCamp/mail-for-good/wiki/How-to-configure-your-Google-API-Keys
We need to add Project creation step for creating a Mail for Good project

I think we need to look into the docs completely and try the setup once to see if the docs are up to date with the new code and config

**Comment by karuppiah7890** [comment]
Similar to #194

**Comment by wadleo** [comment]
The current docs aren't update to with the update Google Api Keys site, I will sent a pull request to fix this soon.

**Comment by karuppiah7890** [comment]
@wadleo Not really. I think it's up to date. Can you be more specific on what's missing ?

**Comment by wadleo** [comment]
yeah, you are correct the guide here matches the Google API management site, but I think developers who are new to using the Google API site would find it difficult because you have to start by selecting a project or creating a new project, before following the steps in the guide. I think that is the only step missing. When the user logins into Google API site, selects the project(mail-for-good) on the top left drop-down or add another project on the dialog box that opens. before following all the steps here. I think this will make the guide more explicit and least confusing. If this is ok with you, I will send a PR to update this guide and the ports mentioned above.

**Comment by karuppiah7890** [comment]
Oh yes. I did think about the project creation

**Comment by karuppiah7890** [comment]
@wadleo Sure! PRs are welcome :smile:

**Comment by wadleo** [comment]
Hi @karuppiah7890 here is my change, https://github.com/wadleo/mail-for-good-wiki but I need help to create a PR to this issue, since it is not possible to send pull request for wikis on github, since there aren't part of the cloned or forked project.

**Comment by karuppiah7890** [comment]
Oh yes, I know. Also, remove the port number 80 in the file, as it's not needed. Just `http://localhost` is fine, as browsers will try to access port 80 by default when the protocol is http as 80 is the default listening port for HTTP servers

Hey @zhakkarn can you help here in merging this Wiki ?

**Comment by wadleo** [comment]
ok I will update the guide

**Comment by AndrewGHC** [comment]
@wadleo Thank you for raising this to our attention.

@karuppiah7890 @wadleo Has this been addressed? If so we can close this.

**Comment by karuppiah7890** [comment]
@AndrewGHC No, it hasn't been addressed

**Comment by wadleo** [comment]
I think this problem has been completely solved now from the commits above. I think we can close this issue now
