### ISSUE TITLE
Uses mail for good without google apps

### ISSUE THREAD

**Issue by educastro** [freeCodeCamp/mail-for-good#220]
Is it possible to use my own domain email and server instead of an email integrated with Google Apps?

**Comment by zhakkarn** [comment]
It depends on what you want to "use" your email for.

If you want to use it to log into an instance of Mail for Good, you can't. As of right now, the only way to login is through the Google+ API which requires you to provide a valid Google account.

But if you want to use your address as the "sending" address during the email blast, you can. For instance, Quincy is using "quincy@freecodecamp.org".

**Comment by zhakkarn** [comment]
As for your own server, yes you can run MfG on it instead of hosting it somewhere else but you'll still have to use AWS because the app is using some of its services to dispatch your emails.

**Comment by educastro** [comment]
@zhakkarn I want to host Mail for Good at AWS but I want to send the emails using my professional domain, the point is that this domain is not integrated with Google Apps and I'm not willing to pay US$5 per month to have it (but if I have no other option I'll). 

Can I login at Mail for Good running at AWS+SES using my personal gmail account and send the emails using my professional domain?

**Comment by karuppiah7890** [comment]
@educastro Yes you can use your personal gmail account just for authentication purposes and use your professional domain to send emails, but the emails are actually sent using SES Email Servers, so, you need to verify your professional domain in AWS SES Dashboard so that you can send mails using any Email ID under your domain :smile: You can also setup DKIM signature for your mails with just a few steps!

**Comment by educastro** [comment]
Amazing! That's exactly what I need, actually I have already integrated my domain with SES! Thank you very much!
