### ISSUE TITLE
Sending from multiple domains possible?

### ISSUE THREAD

**Issue by Rigel772** [freeCodeCamp/mail-for-good#223]
I understand you can configure multiple domains in Amazon SES... can I use them in the app?
Thanks :)

**Comment by karuppiah7890** [comment]
Yes you can :) Just use the appropriate email id ( under the verified
domain ) while creating a campaign and that's it

**Comment by Rigel772** [comment]
fantastic :)

**Comment by 4iar** [comment]
@Rigel772,

It has been a while since I've looked at it, but you may run into issues if you do not also change _SES Email_ in the settings page (to match your new email). 

_SES Email_ in the settings page is used to set up email feedback (bounces, complaints, that type of thing) with AWS.

If your bounces/complaints/deliveries/etc are seeming dodgy on your new email, then this mismatch might be the reason why.

The actual email sending will work fine though as @karuppiah7890 says.

**Comment by karuppiah7890** [comment]
Thanks for the insight @4iar ! I don't know about the complete working of the app, esp SNS and SQS yet. Gotta dive into code. Into golang currently

**Comment by karuppiah7890** [comment]
So, @4iar , does this mean that using M4G you can send Emails from only one mail and properly get the feedback ? because if you use many mail ids, you still can give only one email id in the settings page for the email feedback that you just explained about.
