### ISSUE TITLE
Limit Authentication of other users

### ISSUE THREAD

**Issue by 6ilcarlos** [freeCodeCamp/mail-for-good#242]
Once the Application is running in AWS, How do you manage who can log in and use MFG?

I probably did something wrong, however in my current install, anyone can log in MFG by going to the Whitelabeled URL and using their google credentials. How do you avoid this?

**Comment by karuppiah7890** [comment]
Currently anyone with a Gmail account can login, we have to do some stuff
to create a whitelist of email IDs that can login. And you don't have to
worry too much, they can login, but they have to set their AWS Service
credentials in their account settings to be able to send emails, which you
would have set already for your account. So, you can send emails. And if
they do have their own AWS credentials, then yes, they can login and send
emails using your EC2 for free, but they would be using their own SES, SQS,
SNS.

And I recommend you to not disclose your domain name in public (forums,
tweets) so that people don't use your server for free.

**Comment by 6ilcarlos** [comment]
Great! Thanks for the help! I was thinking about configuring a domain redirect to direct people to other site, however I don't know how that would affect the white label URL.

**Comment by kslr** [comment]
I think I can set the nginx IP check, I was through proxy_pass visit.
However, the use of google landing significance and where?

**Comment by zhakkarn** [comment]
Authentications to the instances are now limited by the new auth strategy.
